version: "3.2"
services:

  deephub:
    image: flowcate/deephub:2.3.0-beta.2
    container_name: deephub-beta
    restart: unless-stopped
    read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    environment:
      - DEEPHUB_PORT=7081
      - DEEPHUB_HOST=0.0.0.0
      - DEEPHUB_CORS=true
      - DEEPHUB_OPENID_CLIENT_NAME=
      - DEEPHUB_OPENID_CONFIG_URL=
      - DEEPHUB_LICENSE_KEY=163177f7-7e9b-4c72-803b-0a5f07f86c29
      - SQLITE_TMPDIR=/data
    ports:
      - "7081"
    volumes:
      - "./hub-data/:/data"
    networks:
      - deephub-net

  deephub-admin-ui:
    image: flowcate/deephub-ui:admin-2.3.0-beta.2-nginx-1.23.3
    container_name: deephub-admin-ui-beta
    tty: true
    stdin_open: true
    read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - deephub
    restart: unless-stopped
    ports:
      - "8080"
    volumes:
      - "./hub-web/:/tmp/run"
      - "./hub-web/nginx/log/:/var/log/nginx"
      - "./hub-web/nginx/cache/:/var/cache/nginx"
      - "./hub-web/nginx/webapp/:/webapp"
    environment:
      - DOCKER_BASE_URL=/deephub/v1
      - DOCKER_ROOT_URL=/deephub
      - DOCKER_WEBSOCKET_URL=
      - DOCKER_APP_BASE_HREF=/deephub-admin-ui/
      - DOCKER_MAP_UPDATES_PER_SECOND=10
      - DOCKER_USE_AUTH=false
      - DOCKER_AUTH_ISSUER=
      - DOCKER_AUTH_REDIRECT_URI=
      - DOCKER_AUTH_CLIENT_ID=
    networks:
      - deephub-net

  deephub-kiosk-ui:
    image: flowcate/deephub-ui:kiosk-2.3.0-beta.2-nginx-1.23.3
    container_name: deephub-kiosk-ui-beta
    tty: true
    stdin_open: true
    read_only: false
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - deephub
    restart: unless-stopped
    ports:
      - "8080"
    volumes:
      - "./hub-web/:/tmp/run"
      - "./hub-web/nginx/log/:/var/log/nginx"
      - "./hub-web/nginx/cache/:/var/cache/nginx"
      - "./hub-web/nginx/conf.d/:/etc/nginx/conf.d"
    environment:
      - NGINX_BASE_HREF=/deephub-kiosk-ui/
      - DEEPHUB_ROOT_URL=/deephub
    networks:
      - deephub-net


  deephub-apache:
    image: httpd:alpine
    container_name: deephub-apache-beta
    restart: unless-stopped
    read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - deephub-admin-ui
    ports:
      - "8081:80"
    volumes:
      - "./apache/conf:/usr/local/apache2/conf"
      - "./apache/htdocs:/usr/local/apache2/htdocs"
      - "./apache/logs:/usr/local/apache2/logs"
    networks:
      - deephub-net

networks:
  deephub-net:
