services:
  deephub:
    image: flowcate/deephub:2.6.0
    restart: unless-stopped
    read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    environment:
      - DEEPHUB_PORT=7081
      - DEEPHUB_HOST=0.0.0.0
      - DEEPHUB_CORS=true
      - DEEPHUB_OPENID_CLIENT_NAME=
      - DEEPHUB_OPENID_CONFIG_URL=
      - DEEPHUB_LICENSE_KEY=<enter your trial license key here>
      - SQLITE_TMPDIR=/data
    ports:
      - "7081"
    volumes:
      - "./hub-data/:/data"
    networks:
      - deephub-net

  deephub-ui:
    image: flowcate/deephub-ui:2.6.0-nginx-1.27.2
    tty: true
    stdin_open: true
    read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - deephub
    restart: unless-stopped
    ports:
      - "8080"
    volumes:
      - "./hub-web/tmp/:/tmp"
      - "./hub-web/nginx/log/:/var/log/nginx"
      - "./hub-web/nginx/cache/:/var/cache/nginx"
      - "./hub-web/nginx/conf.d/:/etc/nginx/conf.d"
      - "./hub-web/data/:/app/deephub-ui-service/data"
    environment:
      - NGINX_BASE_HREF=/deephub-ui/
      - DEEPHUB_ROOT_URL=/deephub
    networks:
      - deephub-net

  deephub-apache:
    image: httpd:alpine
    restart: unless-stopped
    read_only: true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - deephub-ui
    ports:
      - "8081:80"
    volumes:
      - "./apache/conf:/usr/local/apache2/conf"
      - "./apache/htdocs:/usr/local/apache2/htdocs"
      - "./apache/logs:/usr/local/apache2/logs"
    networks:
      - deephub-net

networks:
  deephub-net:
